#!/usr/bin/env node
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = join(root, '.env');
const examplePath = join(root, '.env.example');
const outPath = join(root, 'env.js');

const KEYS = ['MYMEMORY_EMAIL', 'GOOGLE_TRANSLATE_API_KEY'];

function parseEnvFile(filePath) {
  if (!existsSync(filePath)) return {};
  const values = {};
  for (const line of readFileSync(filePath, 'utf8').split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    values[key] = value;
  }
  return values;
}

const fromExample = parseEnvFile(examplePath);
const fromEnv = parseEnvFile(envPath);
const merged = { ...fromExample, ...fromEnv };

const lines = [
  '/** Generated by `npm run env`. Do not edit by hand. */',
  'export const ENV = Object.freeze({',
];

for (const key of KEYS) {
  const value = merged[key] ?? '';
  lines.push(`  ${key}: ${JSON.stringify(value)},`);
}

lines.push('});', '');

writeFileSync(outPath, lines.join('\n'), 'utf8');
console.log(`Wrote ${outPath}`);
